services:
  - type: web
    name: octopus-demo-api
    runtime: docker
    plan: free
    dockerfilePath: ./src/OctopusDeploy.DemoApi/Dockerfile
    envVars:
      - key: ASPNETCORE_URLS
        value: http://0.0.0.0:$PORT